function [qkminus,Pkminus] = timeUpdate(dt,qkminus1,wkminus1,Pkminus1)
    % MEKF, only time update implemented
    w = wkminus1;
    wcross = [0 -w(3) w(2); ...
        w(3) 0 -w(1); ...
        -w(2) w(1) 0];
    cw = cos(norm(w) * dt / 2);
    sw = sin(norm(w) * dt / 2);
    A = eye(3) + sw * wcross / norm(w) + (1 - cw) * wcross^2 / norm(w)^2;
    O = eye(4) + 0.5 * dt * ...
        [0 w(3) -w(2) w(1); ...
        -w(3) 0 w(1) w(2); ...
        w(2) -w(1) 0 w(3); ...
        -w(1) -w(2) -w(3) 0];
    xkminus = zeros([3 1]);
    qkminus = O * qkminus1;
    Pkminus = A * Pkminus1 * A';
end